### ISSUE TITLE
Angular 8 Support

### ISSUE THREAD

**Issue by HMubaireek** [gilsdav/universal-localize-module-loader#6]
This module needs to be updated to work with Angular 8

**Comment by gilsdav** [comment]
Hello,
Thank's for your feedback.

Did you already try using `lazyLoadCallback` and without this module ?

I will try and debug it asap.

**Comment by gilsdav** [comment]
@HMubaireek Are you able to use universal in a simple project (without route translation) ?

`"@nguniversal/express-engine": "^8.0.0-rc.1",
    "@nguniversal/module-map-ngfactory-loader": "v8.0.0-rc.1",`

I think Angular 8 currently doesn't support Universal

**Comment by giacomo** [comment]
Hello @gilsdav, any news on this? 
I want to migrate from greentubes to yours repository ... i think that this package should be required.

best reagards.

**Comment by gilsdav** [comment]
Hello @giacomo,

This package is only required if you are using universal.
As well for the repo of greentubes as for mine.

And as I said in previous comment, Angular 8 doesn't currently support Angular Universal.

Be careful that `ngx-translate-router` have aot problem for now.

**Comment by giacomo** [comment]
Hello @gilsdav,

thank you for your answer - yes i'm using angular universal - and have also aot enabled. 
So as you said, we have to wait till angular 8 supports universal?

🤦‍♂

**Comment by gilsdav** [comment]
@giacomo Probably good new: They released an official version yesterday. 
I will try it but keep in mind that aot build with Angular 8 and my library is currently in progress (discussion) with Angular core devs.

**Comment by gilsdav** [comment]
https://github.com/angular/universal/issues/1194

**Comment by gilsdav** [comment]
Hello,
This library is not needed anymore with new version of `@gilsdav/ngx-translate-router (2.0.1)`

**Comment by gilsdav** [comment]
Check this example for more information: https://github.com/gilsdav/angular-universal-localize-router/tree/angular-8
